# Generated by Django 4.2.1 on 2023-11-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
