# Generated by Django 4.2.6 on 2023-11-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_is_estudiante_userprofile_is_profesor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(default='obamna@usa.soda', max_length=50),
        ),
        migrations.AddField(
            model_name='profesor',
            name='correo',
            field=models.EmailField(default='obamna@usa.soda', max_length=50),
        ),
    ]
