# Generated by Django 4.2.2 on 2023-11-26 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teacher_hora_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hora',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.day'),
        ),
    ]
