# Generated by Django 4.2.2 on 2023-11-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teacher'),
        ('core', '0006_alter_hora_day'),
    ]

    operations = [
    ]
