# Generated by Django 4.2.2 on 2023-11-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_0005_teacher_0006_alter_hora_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hora',
            name='day',
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.TextField(),
        ),
    ]
